apiVersion: v1
kind: Service
metadata:
  name: recipe-service
spec:
  selector:
    app: recipe-service
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
spec:
  selector:
    matchLabels:
      app: recipe-service
  replicas: 1
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: server
          image: malhesidek/recipe-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080

---